set -g default-terminal "screen-256color"


#Change Default TMUX Prefix to “Ctrl-a”
set -g prefix C-q
#unbind C-b
#bind-key C-a send-prefix

bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R

#Change keybinds for splitting windows
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v


set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse


